version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
      - rm -f package-lock.json
      - node -v
      - npm install
      - ls -al
      - pwd
      - ls -al ./src
      - ls -al ./src/components
      - npm run build
artifacts:
  files:
    - build/**/*