version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - ls -al
      - pwd
  build:
    commands:
      - ls -al
      - pwd
      - ls -al ./src
      - ls -al ./src/components
      - npm run build
artifacts:
  files:
    - build/**/*