export default function EditorContentSkills() {
    return [
        { c: '// skills', class: 'comment' },
        { c: '' },
        { c: '<span class="export">export</span> <span class="const">const</span> years_of_professional_experience <span class="light-text">=</span> <span class="number">4</span>' },
        { c: '' },
        { c: '<span class="export">export</span> <span class="const">const</span> total_years_of_experience <span class="light-text">=</span> <span class="number">13</span>' },
        { c: '' },
        { c: '<span class="export">export</span> <span class="const">const</span> skills <span class="light-text">= {</span>' },
        { c: 'typescript: <span class="string">"expert"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'javascript: <span class="string">"expert"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'angular: <span class="string">"expert"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'react: <span class="string">"proficient"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'git: <span class="string">"expert"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'linux: <span class="string">"good"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'graphic_design: <span class="string">"good"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'aws: <span class="string">"good"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'docker: <span class="string">"good"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'nginx: <span class="string">"proficient"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'swift: <span class="string">"proficient"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'business: <span class="string">"good"</span><span class="light-text">,</span>', class: "indent-1"},
        { c: 'security: <span class="string">"good"</span>', class: "indent-1"},
        { c: '<span class="light-text">}</span>' },
    ]
}